# Gambas Action File 3.0

{ Actions
  { Action about
    Text = "About"
    Shortcut = ""
  }
  { Action dice4
    Text = "4 dice"
    Shortcut = ""
  }
  { Action dice5
    Text = "5 dice"
    Shortcut = ""
  }
  { Action dice6
    Text = "6 dice"
    Shortcut = ""
  }
  { Action full_screen
    Text = "Full Screen"
    Shortcut = ""
  }
  { Action new
    Text = "New Game"
    Picture = "images/document-new.png"
  }
  { Action players
    Text = "Players"
    Picture = "images/system-users.png"
  }
  { Action settings
    Text = "Settings"
    Shortcut = ""
  }
  { Action undo
    Text = "Undo"
    Picture = "images/edit-undo.png"
  }
}

