# Gambas Action File 3.0

{ Actions
  { Action about
    Text = "&About"
    Shortcut = ""
  }
  { Action full_screen
    Text = "&Full Screen"
    Shortcut = "Ctrl+Shift+F"
  }
  { Action menu_bar_hide
    Text = "&Hide menu bar"
    Shortcut = "Ctrl+Alt+M"
  }
  { Action menu_bar_show
    Text = "Show menu bar"
    Shortcut = ""
  }
  { Action quit
    Text = "&Quit"
    Shortcut = "Ctrl+Q"
  }
}

