# Gambas Action File 3.0

{ Actions
  { Action about
    Text = "About"
    Shortcut = ""
  }
  { Action full_screen
    Text = "Full Screen"
    Shortcut = "F11"
  }
  { Action help
    Text = "Help"
    Shortcut = ""
  }
  { Action new
    Text = "New Game"
    Shortcut = "Ctrl+N"
  }
  { Action quit
    Text = "Quit"
    Shortcut = "Ctrl+Q"
  }
  { Action settings
    Text = "Settings"
    Shortcut = "S"
  }
  { Action undo
    Text = "Undo"
    Shortcut = "Ctrl+Z"
  }
}

