' Gambas module file

Public Const DEFAULT_CELL_BG As Integer = &HFFFF9F
Public Const DEFAULT_CELL_FG As Integer = &H555555
Public Const DEFAULT_HEADER_BG As Integer = &HFFC71F
Public Const DEFAULT_HEADER_FG As Integer = &H000000
Public Const DEFAULT_INDICATOR_HI_BG As Integer = &H00FF00
Public Const DEFAULT_INDICATOR_HI_FG As Integer = &HFFFFFF
Public Const DEFAULT_INDICATOR_LO_BG As Integer = &HFF0000
Public Const DEFAULT_INDICATOR_LO_FG As Integer = &HFFFFFF
Public Const DEFAULT_MASK As Integer = &HBBBBBB
Public Const DEFAULT_NAME_BG As Integer = &H444444
Public Const DEFAULT_NAME_FG As Integer = &HFFC71F
Public Const DEFAULT_SUM_BG As Integer = &HFFFF00
Public Const DEFAULT_SUM_FG As Integer = &H000000

Public ColorNames As String[] = [("Header column"), ("Header row"), ("Sum"), ("Row"), ("Indicator, high"), ("Indicator, low")]

Public Enum Header, Name, Sum, Cell, IndicatorHi, IndicatorLo, Mask

Private Const KEY_BACKGROUND As String = "Colors/Background_"
Private Const KEY_FOREGROUND As String = "Colors/Foreground_"

Private $aBackgroundDefaults As Integer[] =
  [DEFAULT_HEADER_BG,
  DEFAULT_NAME_BG,
  DEFAULT_SUM_BG,
  DEFAULT_CELL_BG,
  DEFAULT_INDICATOR_HI_BG,
  DEFAULT_INDICATOR_LO_BG,
  DEFAULT_MASK]
Private $aForegroundDefaults As Integer[] =
  [DEFAULT_HEADER_FG,
  DEFAULT_NAME_FG,
  DEFAULT_SUM_FG,
  DEFAULT_CELL_FG,
  DEFAULT_INDICATOR_HI_FG,
  DEFAULT_INDICATOR_LO_FG,
  DEFAULT_MASK]
Private $aBackground As New Integer[$aBackgroundDefaults.Length]
Private $aForeground As New Integer[$aForegroundDefaults.Length]

Public Function GetBackground(Index As Integer) As Integer

  Return $aBackground[Index]

End

Public Sub SetBackground(Index As Integer, Color As Integer)

  $aBackground[Index] = Color

End

Public Function GetForeground(Index As Integer) As Integer

  Return $aForeground[Index]

End

Public Sub SetForeground(Index As Integer, Color As Integer)

  $aForeground[Index] = Color

End

Public Sub Load()

  Dim i As Integer

  For i = 0 To $aBackground.Max
    $aBackground[i] = Settings[KEY_BACKGROUND & i, $aBackgroundDefaults[i]]
  Next

  For i = 0 To $aForeground.Max
    $aForeground[i] = Settings[KEY_FOREGROUND & i, $aForegroundDefaults[i]]
  Next

End

Public Sub Save()

  Dim i As Integer

  Settings.Reload()

  For i = 0 To $aBackground.Max
    Settings[KEY_BACKGROUND & i] = $aBackground[i]
  Next

  For i = 0 To $aForeground.Max
    Settings[KEY_FOREGROUND & i] = $aForeground[i]
  Next

  Settings.Save()

End
